name: Build and Push
on:
  workflow_dispatch:

jobs:
  - name: Echo Info
    run: echo "This is an empty actions file. It was created on main to reveal Build and Push files on other branches"
    run: echo "To test this action, please run it on whatever branch holds your draft"
